/* Generated By:JavaCC: Do not edit this line. PetriConstants.java */
package org.dhbw.ka.ml;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PetriConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ONE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MESSAGE = 6;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int DOUBLE = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int LIST = 12;
  /** RegularExpression Id. */
  int DIGITS = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int ID_ANY = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ONE_LINE_COMMENT>",
    "\"message\"",
    "\"bool\"",
    "\"int\"",
    "\"float\"",
    "\"double\"",
    "\"string\"",
    "\"List\"",
    "<DIGITS>",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "<ID_ANY>",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
  };

}
